### ISSUE TITLE
White screen on iOS devices

### ISSUE THREAD

**Issue by so010** [havfo/multiparty-meeting#120]
iPhones come up with a white screen (for local video?). 
Settings video quality to low and it works. 
Need further testing for identify this bug - have no ios devices :(

**Comment by Astagor** [comment]
I can confirm. On an iPad in Chrome the web page is just white, as if even the index.html would not load. BUT on Safari on the same iPad, everything works perfectly.

**Comment by cryptoprof** [comment]
Confirm same error. In Chrome and Safari browser on Iphone XR. But on Android all work perfect in chrome.

**Comment by misi** [comment]
Which iPhone  wich browser and version? With the latest version (this week on 24  we got a successful test..

**Comment by cryptoprof** [comment]
Thank you for answer. The version of Chrome is 80.0.3987.95
![WhatsApp Image 2020-03-27 at 17 24 48](https://user-images.githubusercontent.com/15214242/77769968-999dad00-7055-11ea-8226-3e8c6570ddbf.jpeg)
In Android 80.0.3987.149(work perfect, but sound have lags)
I will try to ask my friend to update browser in Iphone and tell about result. Thank you again

**Comment by tobias231h** [comment]
I found out that on iOS 13.4, everything is working fine.
However, on older iOS versions (i tested it on iOS 11.1), Safari shows a blank page.

The console throws the error "Unexpected identifier / unexpected token" in file 10.b4c50ba7.chunk.js
So i looked into it and it seems that Safari is somehow corrupting the 10.b4c50ba7.chunk.js file.

It looks like this in other browsers (un-minified):
![Chrome](https://user-images.githubusercontent.com/11997871/77919027-f8a13300-729c-11ea-97c1-3d77e1078799.JPG)

And in Safari for iOS (un-minified):
![Safari-iOS](https://user-images.githubusercontent.com/11997871/77919088-0787e580-729d-11ea-9dbf-915087127a7d.JPG)

Interestingly, the corruption of the file does not always start at the same line. For instance, if I remove line 1 from the script, then the corruption starts one line below the last time.

Maybe this is a limitation in older iOS-Safari versions? Is there a way to reduce the js-file size  by splitting it into multiple files for further debugging?

**Comment by tobias231h** [comment]
Ok turns out there are actually 2 issues.

It seems that older iOS versions have problems with compression. Turning off compression in server.js solved the issue with corrupted files I mentioned earlier.
You could turn off compression only for iOS devices like that (just an example):

        app.use(compression({ filter: shouldCompress }));
	    function shouldCompress (req, res) {
		    if (req.headers['user-agent'].includes('iPhone')) {
		      // don't compress responses with this request header
		      return false
		    }
	   
		    // fallback to standard filter function
		    return compression.filter(req, res)
	     }


This fixes the "white page"-error.

The second issue is this exception: `Unhandled Promise Rejection: TypeError: undefined is not a function (near '...navigator.mediaDevices.addEventListener...')`
Apparently, old iOS-versions don't support this method.

Sadly, I can't test video output because I don't have an iPhone (I used XCode for testing).

**Comment by so010** [comment]
"(i tested it on iOS 11.1)" -> this is ancient technology ;)
Apple supports webRTC API which multiparty meeting is based on since around ios 12.2

**Comment by havfo** [comment]
@tobias231h Thank you so much for testing this! Market share of iOS 11.X and below is ~2,4% compared to iOS 12.X and above. Like @so010 is saying, at some point we have to just leave something behind, and iOS 11.X is probably one of those times.

**Comment by tobias231h** [comment]
Ok I tested a little more and found this out:
- the first iOS version to work with Multiparty-Meeting is iOS 12.4 (12.2 is not working for me)

However, iOS 12.4 (which is the last version for the 5s, 6 and 6 Plus) is only working when I turn off compression, so the beginning of function runHttpsServer() in server.js should probably be changed to something like this:

    app.use(compression({ filter: shouldCompress }));
	function shouldCompress (req, res) {
		if (req.headers['user-agent'].includes('iPhone OS 12_4')) {
		  // don't compress responses with this request header
		  return false
		}
	   
		// fallback to standard filter function
		return compression.filter(req, res)
	 }

I'm not a Javascript programmer so there's probably a better way of checking the iOS version.
This code fragment turns off compression only on iOS 12.4. Compression works (at least for me) on iOS 13.

**Comment by erotavlas-turbo** [comment]
Please read [here](https://webkit.org/blog/8672/on-the-road-to-webrtc-1-0-including-vp8/):
_Safari 11 was the first Safari version to support WebRTC. Since then, we have worked to continue improving WebKit’s implementation and compliance with the spec. I am excited to announce major improvements to WebRTC in Safari 12.1 on iOS 12.2 and macOS 10.14.4 betas, including VP8 video codec support, video simulcast support and Unified Plan SDP (Session Description Protocol) experimental support._
So, it is necessary to use at least safari v12.1 on iOS 12.2 in order to have VP8 video codec support. Moreover, [iOS that does not support a different browser than safari](https://stackoverflow.com/questions/48382150/do-all-browsers-on-ios-use-wkwebview-or-uiwebview) (all the others are safari browser with a different UI).

**Comment by Astagor** [comment]
Hmm, I have an iPad with iOS 13.3.1 and in Safari the multiparty-meeting works, but in Chrome not. So there is a difference.

**Comment by erotavlas-turbo** [comment]
[Apple Developer Guidelines](https://developer.apple.com/app-store/review/guidelines/)
_2.5.6 Apps that browse the web must use the appropriate WebKit framework and WebKit Javascript._

Chrome, Edge, Firefox, Brave, and others have to use Safari’s WebKit-based browser engine in their apps, as Apple doesn’t allow rival rendering engines on iOS. This allows Apple to control the security and updates of how web content is rendered on devices in every app.

So if Safari works while other browsers not, there is something new. I could find an answer.

**Comment by Astagor** [comment]
Back to this topic. Now, as the unsupported browser is in place I can see what is happening on my iPad
iOS ver. 13.4.1
Chrome ver. 83.0.4103.63 
On Safari MM works fine.
On Chrome I get the browser unsupported dialog.

**Comment by Astagor** [comment]
I did some more debugging and it seems that for Chrome on iOS
navigator.mediaDevices is undefined
That is why we get browser not supported.

**Comment by Astagor** [comment]
OK got it now: http://www.openradar.me/33571214
It seems that getUserMedia is not enabled for applications that use a WKWebView.
So Chrome on iOS will not work. Or any other browser. Only Safari will work.
We can close this one.

**Comment by Astagor** [comment]
My recommendation would be to change the error message in UnsupportedBrowser.js and index.html so we list not only browsers by combination of OS and Browser. Maybe only for mobile devices.

**Comment by misi** [comment]
> OK got it now: http://www.openradar.me/33571214
> It seems that getUserMedia is not enabled for applications that use a WKWebView.
> So Chrome on iOS will not work. Or any other browser. Only Safari will work.
> We can close this one.

IMHO we need to add an exception on iOS and support chrome.

**Comment by misi** [comment]
I close this issue and do the follow up on #108
